### ISSUE TITLE
Regression compiling somewhere between 1.12.0 and 1.14.2 

### ISSUE THREAD

**Issue by ScruffR** [spark/particle-cli#259] opened 2016-06-16 13:11 UTC
I've had a member on OSX 10.9.5 who could not build his project containing the most recent Blynk library (but hasn't to do with that lib).
While I could build successfully on my Windows machines (the exact same project files and structure) he always got this

``` text
 particle compile photon .

Compiling code for photon

Including:
/Users/AirMonks/Hopper/ButtePhotonHopper/parallex/pingBlynk/main_ping.ino
/Users/AirMonks/Hopper/ButtePhotonHopper/parallex/pingBlynk/firmware/blynk/BlynkApi.h
/Users/AirMonks/Hopper/ButtePhotonHopper/parallex/pingBlynk/firmware/blynk/BlynkApiParticle.h
/Users/AirMonks/Hopper/ButtePhotonHopper/parallex/pingBlynk/firmware/blynk/BlynkConfig.h
/Users/AirMonks/Hopper/ButtePhotonHopper/parallex/pingBlynk/firmware/blynk/BlynkDebug.h
/Users/AirMonks/Hopper/ButtePhotonHopper/parallex/pingBlynk/firmware/blynk/BlynkDetectDevice.h
/Users/AirMonks/Hopper/ButtePhotonHopper/parallex/pingBlynk/firmware/blynk/BlynkHandlers.h
/Users/AirMonks/Hopper/ButtePhotonHopper/parallex/pingBlynk/firmware/blynk/BlynkParam.h
/Users/AirMonks/Hopper/ButtePhotonHopper/parallex/pingBlynk/firmware/blynk/BlynkParticle.h
/Users/AirMonks/Hopper/ButtePhotonHopper/parallex/pingBlynk/firmware/blynk/BlynkProtocol.h
/Users/AirMonks/Hopper/ButtePhotonHopper/parallex/pingBlynk/firmware/blynk/BlynkProtocolDefs.h
/Users/AirMonks/Hopper/ButtePhotonHopper/parallex/pingBlynk/firmware/blynk/BlynkSimpleParticle.h
/Users/AirMonks/Hopper/ButtePhotonHopper/parallex/pingBlynk/firmware/blynk/BlynkUtility.h
/Users/AirMonks/Hopper/ButtePhotonHopper/parallex/pingBlynk/firmware/blynk/BlynkWidgets.h
/Users/AirMonks/Hopper/ButtePhotonHopper/parallex/pingBlynk/firmware/blynk/WidgetBridge.h
/Users/AirMonks/Hopper/ButtePhotonHopper/parallex/pingBlynk/firmware/blynk/WidgetLCD.h
/Users/AirMonks/Hopper/ButtePhotonHopper/parallex/pingBlynk/firmware/blynk/WidgetLED.h
/Users/AirMonks/Hopper/ButtePhotonHopper/parallex/pingBlynk/firmware/blynk/WidgetTerminal.h
/Users/AirMonks/Hopper/ButtePhotonHopper/parallex/pingBlynk/firmware/blynk/blynk.h
/Users/AirMonks/Hopper/ButtePhotonHopper/parallex/pingBlynk/firmware/blynk/BlynkDebug.cpp
/Users/AirMonks/Hopper/ButtePhotonHopper/parallex/pingBlynk/firmware/blynk/BlynkHandlers.cpp
/Users/AirMonks/Hopper/ButtePhotonHopper/parallex/pingBlynk/firmware/blynk/blynk.cpp
attempting to compile firmware
Compile failed. Exiting.
```

This was with node 4.2.4 and CLI 1.14.2
But using CLI 1.12.0 plus a `particle.include` file worked like a charm

**Comment by technobly** [comment] 2016-06-16 13:18
Thanks for continuing the dig into this problem ScruffR!  My guess is there are still left over file handling bugs from the v1.13.0 changes which introduced the ability to compile subdirectories.  "Compile failed. Exiting." is an node.js exception indication.

**Comment by monkbroc** [comment] 2016-06-16 13:52
I'll be honest that I didn't test all the cases of how people compile firmware because there's no specification anywhere of all use cases that should work. Take the `particle.include` for example. Is it something that people really use and why?

**Comment by technobly** [comment] 2016-06-16 15:04
`particle.include` was previously the only way to include files from subdirectories.

**Comment by technobly** [comment] 2016-06-16 15:07
`particle.include` is not failing though, it's the new `.` that just recursively adds all files from all subdirectories.  And it doesn't happen for everyone... for example I can use `.` just fine.

It might be worth including the entire directory structure in the first post @ScruffR but didn't you also say that you could compile these same files without a problem?  So it's those files + the OS + environment that's an issue?

**Comment by ScruffR** [comment] 2016-06-16 15:15
The file structure didn't make any difference. I tried different setups and was always able to build but Morgan couldn't get it to build on his Mac but on an ol' Windows machine he dug up.

**Comment by kennethlimcp** [comment] 2016-06-17 12:43
Using node 5.7, CLi 1.12.0,

```
KENMBP:RGBMatrixPanel-Shield-V4-Test-app kennethlimcp$ pcp .

Compiling code for photon

Including:
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/Adafruit_mfGFX.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/ArduinoFiles.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/ArduinoStream.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/bufstream.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatApiConstants.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatFile.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatFileSystem.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatLib.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatLibConfig.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatStructs.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatVolume.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FmtNumber.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/font3x5.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/font5x5.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/fonts.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FreeStack.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/fstream.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/gamma.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/GIFDecoder.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/ios.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/iostream.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/istream.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/ostream.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/RGBmatrixPanel.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdFat.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdFatConfig.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdInfo.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdSpi.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdSpiCard.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SoftSPIParticle.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SparkIntervalTimer.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/StdioStream.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SysCall.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SystemInclude.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/Adafruit_mfGFX.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/AnimatedGIFs.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatFile.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatFileLFN.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatFilePrint.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatFileSFN.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatVolume.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FilenameFunctions.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FmtNumber.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/fonts.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/fstream.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/GIFParseFunctions.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/istream.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/LZWFunctions.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/ostream.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/RGBmatrixPanel.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdFat.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdSpiCard.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdSpiParticle.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SparkIntervalTimer.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/StdioStream.cpp
attempting to compile firmware 
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/Adafruit_mfGFX.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/ArduinoFiles.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/ArduinoStream.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/bufstream.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatApiConstants.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatFile.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatFileSystem.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatLib.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatLibConfig.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatStructs.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatVolume.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FmtNumber.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/font3x5.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/font5x5.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/fonts.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FreeStack.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/fstream.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/gamma.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/GIFDecoder.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/ios.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/iostream.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/istream.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/ostream.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/RGBmatrixPanel.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdFat.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdFatConfig.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdInfo.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdSpi.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdSpiCard.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SoftSPIParticle.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SparkIntervalTimer.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/StdioStream.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SysCall.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SystemInclude.h
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/Adafruit_mfGFX.cpp
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/AnimatedGIFs.cpp
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatFile.cpp
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatFileLFN.cpp
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatFilePrint.cpp
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatFileSFN.cpp
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatVolume.cpp
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FilenameFunctions.cpp
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FmtNumber.cpp
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/fonts.cpp
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/fstream.cpp
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/GIFParseFunctions.cpp
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/istream.cpp
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/LZWFunctions.cpp
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/ostream.cpp
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/RGBmatrixPanel.cpp
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdFat.cpp
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdSpiCard.cpp
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdSpiParticle.cpp
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SparkIntervalTimer.cpp
pushing file: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/StdioStream.cpp
downloading binary from: /v1/binaries/5763f038a9fe98a0545382b6
saving to: photon_firmware_1466167338300.bin
Memory use: 
   text	   data	    bss	    dec	    hex	filename
  26060	    180	  18980	  45220	   b0a4	
Compile succeeded.
Saved firmware to: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/photon_firmware_1466167338300.bin
```

**Comment by kennethlimcp** [comment] 2016-06-17 12:50
I wonder what's going on...

```
KENMBP:~ kennethlimcp$ node --version
v5.7.0
KENMBP:~ kennethlimcp$ p --version
1.14.2
KENMBP:~ kennethlimcp$ desk
KENMBP:Desktop kennethlimcp$ cd testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/
KENMBP:RGBMatrixPanel-Shield-V4-Test-app kennethlimcp$ pcp .

Compiling code for photon

Including:
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/Adafruit_mfGFX.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/ArduinoFiles.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/ArduinoStream.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/bufstream.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatApiConstants.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatFile.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatFileSystem.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatLib.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatLibConfig.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatStructs.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatVolume.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FmtNumber.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/font3x5.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/font5x5.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/fonts.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FreeStack.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/fstream.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/gamma.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/GIFDecoder.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/ios.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/iostream.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/istream.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/ostream.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/RGBmatrixPanel.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdFat.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdFatConfig.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdInfo.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdSpi.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdSpiCard.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SoftSPIParticle.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SparkIntervalTimer.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/StdioStream.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SysCall.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SystemInclude.h
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/Adafruit_mfGFX.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/AnimatedGIFs.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatFile.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatFileLFN.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatFilePrint.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatFileSFN.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FatVolume.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FilenameFunctions.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/FmtNumber.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/fonts.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/fstream.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/GIFParseFunctions.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/istream.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/LZWFunctions.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/ostream.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/RGBmatrixPanel.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdFat.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdSpiCard.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SdSpiParticle.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/SparkIntervalTimer.cpp
    /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/StdioStream.cpp
attempting to compile firmware 
downloading binary from: /v1/binaries/5763f206ce32549028274324
saving to: photon_firmware_1466167796409.bin
Memory use: 
   text	   data	    bss	    dec	    hex	filename
  26060	    180	  18980	  45220	   b0a4	
Compile succeeded.
Saved firmware to: /Users/kennethlimcp/Desktop/testfolder/testfolderfolder/RGBMatrixPanel-Shield-V4-Test-app/photon_firmware_1466167796409.bin
KENMBP:RGBMatrixPanel-Shield-V4-Test-app kennethlimcp$ 
```


Can we see a `ls` of that directory?

**Comment by ScruffR** [comment] 2016-06-17 13:41
I had him move the whole lot into a temp folder directly in his `/Users` and he had it `chmod 777`
I sent him a zip of the project that built on my machine but it didn't build on his.
His tar that he sent to me - which didn't build on his - built just fine on mine.

I guess I could send you both archives but I don't think it's in the files. We both just downloaded the Blynk repo 0.37 and used the `firmware` folder without the `examples` subfolder or any of the 
The only private thing was his `.ino`

**Comment by kennethlimcp** [comment] 2016-06-17 14:07
@ScruffR, i tried to create a `._` file as well but no dice. I would recommend reinstalling CLI just to be sure. i got some weird error just now and a reinstallation fixed it. (i would blame npm2 for the weirdness)

**Comment by ScruffR** [comment] 2016-06-17 14:10
We deinstalled reinstalled node and CLI several times, but no change.
I can ask Morgan if he'd be willing to try 1.14.2 again and maybe try if a `particle.ignore` file would help.

**Comment by kennethlimcp** [comment] 2016-06-17 14:11
From the above, you can clearly see that mine is resulting in an error. If i move the `.ino` file into the subdir, it will compile fine.

**Comment by ScruffR** [comment] 2016-06-17 14:23
Actually no, above I see in both cases
```text
saving to: photon_firmware_1466167338300.bin
Memory use: 
   text    data     bss     dec     hex filename
  26060     180   18980   45220    b0a4 
Compile succeeded.
```
and
```text
saving to: photon_firmware_1466167796409.bin
Memory use: 
   text    data     bss     dec     hex filename
  26060     180   18980   45220    b0a4 
Compile succeeded.
```
I don't see an error.
But if you had an error with 1.12.0 without `particle.include` that'd be no surprise.

**Comment by ScruffR** [comment] 2016-06-26 19:33
@technobly, a new incident in this direction
https://community.particle.io/t/cli-compile-fails/23970

**Comment by MaxSharx** [comment] 2016-06-29 20:16
Yes, that's me. Thanks ScruffR. It's really annoying but I'm unable to compile but simple projects. Is anybody doing a RCA or any analysis on this issue? Regards, Marcus

**Comment by ScruffR** [comment] 2016-07-10 17:06
@monkbroc maybe a new instance of the same problem
https://community.particle.io/t/compiling-using-cli-with-multiple-directories/24273/3

**Comment by m-mcgowan** [comment] 2017-01-27 14:41
I couldn't reproduce that with 1.19.2...we have done a lot of work with the compiler in the CLI so I'm guessing this has been fixed in the interim.

**Closed by m-mcgowan** 2017-01-27 14:41 UTC
Labels: bug
