### ISSUE TITLE
Send product_id=6 on `particle keys send <device-id> some-key.pub.pem` for photon

### ISSUE THREAD

**Issue by joegoggins** [spark/particle-cli#90] opened 2015-08-07 22:17 UTC
In our automation scripts that test devices against different clouds, we frequently use the `particle keys send` command to allow a device to connect to it. The API endpoint behind this command accepts a product_id parameter.  Can we find a way to pass this information along with the "send key" command too? Perhaps just an optional `--product-id` param would do the trick.

**Comment by emilyrose** [comment] 2015-08-07 22:34
Oh wow! is this why my devices 'randomly' start showing up as Cores?

**Comment by joegoggins** [comment] 2015-08-07 22:45
No. Different reason. That was due to a recently fixed bug in the Web IDE that overwrote the product_id.

This feature enhancement idea mainly helps when pointing devices at different clouds that haven't already connected and been claimed to a user account or that don't have ANY keys stored in the cloud's database.

**Comment by brycekahle** [comment] 2016-01-14 01:54
Duplicate of #155

**Closed by brycekahle** 2016-01-14 01:54 UTC
Labels: enhancement
