### ISSUE TITLE
Particle CLI Installer Failure

### ISSUE THREAD

**Issue by technobly** [spark/particle-cli#273] opened 2016-08-28 15:41 UTC
Re: https://community.particle.io/t/photon-flashing-cyan-with-red-bursts-solved/25113/5

BDub said:

> Here's a direct link for Windows: https://binaries.particle.io/cli/installer/windows/ParticleCLISetup.exe

Michele replied:

> But when I ran the setup program it opened the installer dialog and then popped up an error "Your internet connection seems to be not permitted or dropped out!  Please reconnect and click Retry to resume installation."
> 
> Well there's nothing wrong with my Internet connection.  I even tried this on a different PC and got the same error.  So I'm not going to get aggravated, I'm just going to ask for more help.  How do I get this installed?
> 
> Just out of curiosity, does this try to talk to a server in China?  Because I have all of .cn blocked at my router, as well as a number of other malware-type Internet domains.

@monkbroc would you please look into this error, because the alternative is a whole lot of no fun on Windows... installing dfu-util, openssl, PATH updates, etc.. Thanks!

**Comment by monkbroc** [comment] 2016-08-29 13:44
I don't think I'll be able to get to this for a while. It sounds like a weird issue with this person's computer, maybe ad blocker / antivirus.

I'm curious why you mention openssl in relation to the CLI.

**Comment by technobly** [comment] 2016-08-29 16:22
The CLI uses openssl for the keys command.  In particular the `particle keys doctor` command.  Does the installer also install openssl?

**Comment by monkbroc** [comment] 2016-08-29 16:25
No, it does not. I wasn't aware of the details of the key doctor command.

**Comment by m-mcgowan** [comment] 2017-02-06 23:49
The CLI installer includes SSL since 0.2.0

**Comment by m-mcgowan** [comment] 2017-02-07 00:15
I couldn't reproduce this with the latest installer. It would be good to have the installation log to see how far the installer had come before failing. The OP mentions that various domains are blocked (.cn and various 'malware-type' domains) so I would guess that is the cause of the issue here. 

Closing this as unreproducible. Happy to re-open when more information is available.

**Closed by m-mcgowan** 2017-02-07 00:15 UTC
Labels: bug
