### ISSUE TITLE
Library can't be updated on characters case changed

### ISSUE THREAD

**Issue by aliktab** [spark/particle-cli#345] opened 2017-02-22 16:21 UTC
I'm making my own library and "particle library upload" doesn't actually upload my library if I've change the only upper or lower case of some letters. It make me unable to fix bugs sometimes. I have to change something else to make new version of library available for main application.

Operating System: 5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8

**Comment by monkbroc** [comment] 2017-02-22 21:31
I'd like to make sure I understand: you update the code in the `src` directory of a private version of a library, do `particle library upload` then compile an app in another directory that depends on that private library version with `particle compile photon`. In some cases the old code is used instead of the new code.

Is that right?

**Comment by aliktab** [comment] 2017-02-23 00:16
Yes, that's right. For example in case if I change the only lower case to upper case of some identifiers. I'm using desktop IDE if it is important to know.

**Comment by monkbroc** [comment] 2017-02-23 00:18
I think I know the cause. The fix is server side. I'll let you know when
it's fixed.

Thanks for reporting this!

**Comment by aliktab** [comment] 2017-02-23 00:28
Thanks a lot!

**Comment by monkbroc** [comment] 2017-03-30 20:16
I wanted to let you know this is now fixed.

**Closed by monkbroc** 2017-03-30 20:16 UTC
Labels: bug, confirmed
