### ISSUE TITLE
Server key address output incorrect for Electron using TCP

### ISSUE THREAD

**Issue by towynlin** [spark/particle-cli#279] opened 2016-09-17 20:32 UTC
Given I have an Electron with valid keys for the UDP and TCP servers
When I run `particle keys protocol tcp`
And I run `particle keys address`
Then I expect the output to be `tcp://device.spark.io:5683`
But instead I currently see `tcp://$id.udp.particle.io:5683`

It seems as though the [CLI implementation of `particle keys address`](https://github.com/spark/particle-cli/blob/b64252a42eae7b89b222011554a58777d29e8b08/commands/KeyCommands.js#L588-L595) is correctly checking the protocol and correctly changing the port, but incorrectly handling the host name, allowing the CLI default even to be overridden incorrectly.

**Comment by m-mcgowan** [comment] 2017-01-27 13:15
I couldn't reproduce this with CLI 1.19.2. It printed out the correct address.

**Comment by m-mcgowan** [comment] 2017-02-07 18:17
The keys and protocol handling has been revamped, so this issue should be fixed, although I couldn't reproduce it.

**Closed by m-mcgowan** 2017-02-07 18:17 UTC
Labels: bug
